### ISSUE TITLE
Lecture slide color bug

### ISSUE THREAD

**Issue by SergheiMazur** [lewagon/ui-components#7]
Link: https://kitt.lewagon.com/karr/lectures/front/01-html-css/index.html?title=HTML%20&%20CSS%20basics#/6/9

".img-circle" - has a **color:red**

And all other classes have a **color:#FA4D6A**

Do you think this is a bug?

**Comment by arthur-littm** [comment]
Yep, fixed https://github.com/lewagon/karr/commit/42c846c8dae2cc034552c04dbf0a0f4a1102b365
